# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "public_network", ip: "172.16.2.193"

  config.vm.synced_folder "./data", "/DATA"

  config.vm.hostname = "host3"
end
